- name: Set up db config
  template: src=database.yml.j2 dest={{be_app_path}}/config/database.yml

# zzet.rbenv puts all the rbenv stuff in profile for some reason
# so we gotta use login shells to do this stuff
- name: Install bundle gems
  remote_user: "{{ deployer_user.name }}"
  command: chdir={{ be_app_path }}
           bash -lc "RAILS_ENV={{be_app_env}} bundle install
             --without test development contests_development --deployment"
  tags: [be_deploy, bundle]

- name: Ensure env_config.yml file present
  stat: path={{ be_app_path }}/config/env_config.yml
  register: env_config_file
  tags: [be_deploy]

- name: Ask for env_config.yml
  debug: msg="You've got to upload env_config.yml to {{be_app_path}}/config to continue"
  when: env_config_file.stat.exists != true
  tags: [be_deploy]

- name: Wait one day for env_config.yml to get put on the server
  wait_for: path={{be_app_path}}/config/env_config.yml state=present timeout=86400
  when: env_config_file.stat.exists != true
  tags: [be_deploy]

- name: Ensure secrets.yml file present
  stat: path={{ be_app_path }}/config/secrets.yml
  register: secrets_file
  tags: [be_deploy]

- name: Ask for secrets.yml
  debug: msg="You've got to upload secrets.yml to {{be_app_path}}/config to continue"
  when: secrets_file.stat.exists != true
  tags: [be_deploy]

- name: Wait one day for secrets.yml to get put on the server
  wait_for: path={{be_app_path}}/config/secrets.yml state=present timeout=86400
  when: secrets_file.stat.exists != true

- name: Precompile Assets
  remote_user: "{{ deployer_user.name }}"
  command: chdir={{ be_app_path }}
           bash -lc "bundle exec rake assets:precompile RAILS_ENV={{be_app_env}}"
  tags: [precompile_assets,be_deploy]
  when: precompile_assets

  tags: [be_deploy]
