- name: Ensure repo is defined
  fail: msg="App Repo is not defined. Please define it in {{ tapefiles_dir }}/tape_vars.yml"
  when: (be_app_repo is undefined or be_app_repo is none) and (fe_app_repo is undefined or fe_app_repo is none)

- name: Ensure app name is defined
  fail: msg="app_name is not defined. Please define it in {{ tapefiles_dir }}/tape_vars.yml"
  when: app_name is undefined or app_name is none

- name: apt-get update upgrade
  apt: update_cache=yes  upgrade=safe

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- include: basic_packages.yml
- include: swapfile.yml
