- name: Create deployer groups
  group: name={{ item }} state=present
  with_items: deployer_user.groups

- name: Ensure deployer user is present
  user: name={{ deployer_user.name }} state=present append=yes shell=/bin/bash

- name: Ensure deployer user is in its groups
  user: name={{ deployer_user.name }} groups={{ item }} state=present append=yes shell=/bin/bash
  with_items: deployer_user.groups

- name: Ensure deployer user owns its own homedir
  file: path=/home/deployer state=directory owner=deployer

- include: keys.yml
